### ISSUE TITLE
p2pd test nat traversal

### ISSUE THREAD

**Issue by justheuristic** [learning-at-home/hivemind#149]
![image](https://user-images.githubusercontent.com/3491902/109007737-89ef7400-76bd-11eb-9320-959a0e20963b.png)

Create a simple setup with 3 nodes where
- node S1 starts first; it is available publicly; it is a full DHT node
- nodes A and B are _bootstrap_-ed from S1 and 
- all nodes use QUIC with ~secio~ tls/noise

TODO:
- [x] check that nodes A and B can communicate directly if they are **not** behind NAT (localhost-only)
- [x] check that nodes A and B can communicate if they **are** behind NAT (ping me if you need access to a VM for S1)

**Comment by MaximKsh** [comment]
## Setup 1
S1, A and B in the same LAN
run S1:
`./p2pd -quic=1 -tls=1 -connManager=1 -natPortMap=1 -autonat=1 -dhtServer=1 -hostAddrs=/ip4/127.0.0.1/udp/34000/quic -listen=/ip4/127.0.0.1/tcp/35000`
run A:
`./p2pd -quic=1 -tls=1 -connManager=1 -natPortMap=1 -autonat=1 -dhtClient=1 -b -bootstrapPeers=/ip4/127.0.0.1/udp/34000/quic/p2p/<S1_PeerID>  -hostAddrs=/ip4/127.0.0.1/udp/34001/quic -listen=/ip4/127.0.0.1/tcp/35001`
run B:
`./p2pd -quic=1 -tls=1 -connManager=1 -natPortMap=1 -autonat=1 -dhtClient=1 -b -bootstrapPeers=/ip4/127.0.0.1/udp/34000/quic/p2p/<S1_PeerID>  -hostAddrs=/ip4/127.0.0.1/udp/34002/quic -listen=/ip4/127.0.0.1/tcp/35002`

* dhtServer = 1 enables routing via dht
* b enables bootstrapping (connect to well-known nodes for peer discovery)
* bootstrapPeers - list of well-known nodes for bootstrapping

Node A and B can interact with each other using PeerID

## Setup 2
A and B in different networks and covered by different NAT's

A: 
`./p2pd -quic=1 -tls=1 -connManager=1 -natPortMap=1 -autonat -dhtClient=1 -b  -hostAddrs=/ip4/0.0.0.0/udp/44001/quic -listen=/ip4/127.0.0.1/tcp/45001`
B:
`./p2pd -quic=1 -tls=1 -connManager=1 -natPortMap=1 -autonat -dhtClient=1 -b -hostAddrs=/ip4/0.0.0.0/udp/44002/quic -listen=/ip4/127.0.0.1/tcp/45002`

Nodes connect to global IPFS peers and get peer addresses. 
For example:
```
Peer Addrs:
/ip4/192.168.1.150/udp/44002/quic     # peer address in LAN
/ip4/127.0.0.1/udp/44002/quic              # peer address on the same machine
/ip4/109.252.14.143/udp/18760/quic   # peer address beyond NAT. This address became available via NAT Hole punching.
```

Node A and B can interact with each other using PeerID

## Setup 3
A and B in different networks, covered by different NAT's and bootstrapped to S1. 
S1:
`./p2pd -quic=1 -tls=1 -connManager=1 -natPortMap=1  -dhtServer=1 -hostAddrs=/ip4/0.0.0.0/udp/5000/quic -listen=/ip4/0.0.0.0/tcp/5001`

A:
`./p2pd -quic=1 -tls=1 -connManager=1 -natPortMap=1 -autonat=1 -dhtClient=1 -b -bootstrapPeers=/ip4/92.53.78.235/udp/5000/quic/p2p/<S1 PeerID>  -hostAddrs=/ip4/0.0.0.0/udp/44001/quic -listen=/ip4/127.0.0.1/tcp/45001
`
B:
`./p2pd -quic=1 -tls=1 -connManager=1 -natPortMap=1 -autonat=1 -dhtClient=1 -b -bootstrapPeers=/ip4/92.53.78.235/udp/5000/quic/p2p/<S1 PeerID> -hostAddrs=/ip4/0.0.0.0/udp/44002/quic -listen=/ip4/127.0.0.1/tcp/45002`

Setup 3 is quite similar with Setup 1. But I faced a problem: A and B don't get their "beyond NAT" addresses (like in Setup2):
```
Peer Addrs:
/ip4/192.168.1.150/udp/44002/quic
/ip4/127.0.0.1/udp/44002/quic
```
Because of this peers A and B can't interact with each other because they have not addresses for that interaction. I think the problem is in the settings of S1, but I don't know solution yet


## Sender/receiver example
Let A be a receiver
```
control_addr = Multiaddr('/ip4/127.0.0.1/tcp/45002') # p2pd listen address
listen_addr = Multiaddr(f'/ip4/127.0.0.1/tcp/{find_open_port()}') # py binding listen address. Any free port.
client = p2pclient.Client(control_addr, listen_addr)
async def handle(stream_info, stream):
    pass 
await client.stream_handler('some_stream_key', handle)
async with client.listen():
end_of_the_universe = asyncio.Event()
await end_of_the_universe.wait() 
```
Peer B aka sender
```
control_addr = Multiaddr('/ip4/127.0.0.1/tcp/45001') #p2pd listen address
client = p2pclient.Client(control_addr)
receiver_id = ID.from_base58(A Peer ID)
stream_info, stream = await client.stream_open(receiver_id, ('some_stream_key',))
await stream.close()
```
It works in Setup1 and Setup2. In Setup3 B can find A addresses in DHT but can't reach because addresses are local (127.0.0.1 and 192.168.1.0/24)


Useful links

[https://github.com/libp2p/go-libp2p-examples](https://github.com/libp2p/go-libp2p-examples)
[https://github.com/libp2p/go-libp2p-daemon/blob/bfa207ed34c27947f0828a4ae8d10bda62aa49a9/p2pd/main.go](https://github.com/libp2p/go-libp2p-daemon/blob/bfa207ed34c27947f0828a4ae8d10bda62aa49a9/p2pd/main.go)
[https://github.com/libp2p/go-libp2p-daemon/blob/bfa207ed34c27947f0828a4ae8d10bda62aa49a9/p2pd/main.go](https://github.com/libp2p/go-libp2p-daemon/blob/bfa207ed34c27947f0828a4ae8d10bda62aa49a9/p2pd/main.go)

**Comment by MaximKsh** [comment]
Setup 3 works if we have 4 or more public servers (S1-Sn, n >= 4). Indeed, S1-Sn must be connected with each other.

**Comment by justheuristic** [comment]
(same, but longer)

Resolution: we can reliably traverse NAT in three circumstances:
* current DHT contains at least 4 nodes on different IPs with -autonat enabled (and without NAT)
* the participant knows his IP address and port (e.g. with manual forwarding)
* we use IPFS DHT

For convenience, we will need to:
- maintain backbone libp2p nodes for hivemind (gcp, aws, nora, volunteer hosts)
- allow passing IP address directly to P2P
