### ISSUE TITLE
Set a wait time for other peers to join

### ISSUE THREAD

**Issue by elricwan** [learning-at-home/hivemind#455]
**Is your feature request related to a problem? Please describe.**

In my experiment in pretrianing BERT, I use two machines, each has four gpus. I set the target_batch_size to be 4096 and the train_batch_size for each gpu as 16. In the middle of the training, one of the machine restart and I would like to reconnect to the previous server, however, the peer cannot join as shown below:
```
Feb 11 14:19:34.352 [INFO] bert_experiment accumulated 64 samples for epoch #15040 from 4 peers. ETA 16.79 sec (refresh in 9.59 sec)
Feb 11 14:19:35.275 [INFO] Peer is out of sync
Feb 11 14:19:35.446 [INFO] Downloading parameters from peer QmWhCEDcUaenbLRsdpLfDobCC6ikTu1gzthh32sSSiV8je

 File "/home/protago/miniconda3/envs/hivemind/lib/python3.8/site-packages/hivemind/optim/optimizer.py", line 686, in load_state_from_peers
    self.state_averager.load_state_from_peers(timeout=self.load_state_timeout, **kwargs)
  File "/home/protago/miniconda3/envs/hivemind/lib/python3.8/site-packages/hivemind/optim/state_averager.py", line 650, in load_state_from_peers
    loaded_state = super().load_state_from_peers(**kwargs)
  File "/home/protago/miniconda3/envs/hivemind/lib/python3.8/site-packages/hivemind/averaging/averager.py", line 681, in load_state_from_peers
    return future.result(timeout=timeout) if wait else future
  File "/home/protago/miniconda3/envs/hivemind/lib/python3.8/site-packages/hivemind/utils/mpfuture.py", line 257, in result
    return super().result(timeout)
  File "/home/protago/miniconda3/envs/hivemind/lib/python3.8/concurrent/futures/_base.py", line 446, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError

Feb 13 00:45:14.939 [INFO] Downloading parameters from peer QmRJStYkg1mUpe2KHYUVCwHuPg74uiqnrG3LZx7JgZvnti
Feb 13 00:46:14.408 [INFO] Finished downloading state from QmXX27qBPWuyHvt2jpnKzq1d2X7zJ6g6vRcr6sR7vc4ckL
Feb 13 00:54:05.409 [INFO] Finished downloading state from QmRJStYkg1mUpe2KHYUVCwHuPg74uiqnrG3LZx7JgZvnti

```

The BERT base model is not huge and the 4096 target_batch_size suppose to give enough time for peer to join, at least when start simultaneously at the beginning, two machines with eight peers work just fine. But in the middle of the experiment, the disconnect peer cannot re-join. (It takes around 1 minute download from QmXX27qBPWuyHvt2jpnKzq1d2X7zJ6g6vRcr6sR7vc4ckL and 5 minutes from QmRJStYkg1mUpe2KHYUVCwHuPg74uiqnrG3LZx7JgZvnti)

![Screen Shot 2022-02-11 at 2 32 13 PM](https://user-images.githubusercontent.com/33402371/153657615-49d3ba35-98f4-4f33-a45e-124b63e7a96d.png)

**Describe the solution you'd like**
I am wondering if there is a way to slow down the running peers or force running peer to wait a certain amount of time when new peer try to join?

**Describe alternatives you've considered**
Or could you give me a method to reconnect the lost peers?

**Additional context**

**Comment by justheuristic** [comment]
Hi! (and sorry for the delay - we somehow overlooked this)

Currently we have no such mechanism. The rationale for this is that if there are 50+ peers, someone tries to join every minute and waiting for them would mean not training at all.

There are a few things that you can do to make them work on your end:
- compress the downloaded state -- optimizer [has `load_state_compression` parameter](https://learning-at-home.readthedocs.io/en/latest/modules/optim.html) similar to other compression strategies. 16-bit compression will turn 5 minutes into 2.5.
- use a more compact optimizer. 8bit Adam / LAMB / SGD have need ~3.5x less space for statistics, making it ~2x faster to download. See [bitsandbytes](https://github.com/facebookresearch/bitsandbytes). In https://github.com/NCAI-Research/CALM , you can find an example of 8bit offloaded LAMB with hivemind optimizer.
- if everything else fails - you can override the synchronization mechanizm once when a peer downloads their state. The way you can do this is:
```
while my_optimizer._should_load_state_from_peers():
  my_optimizer.load_state_from_peers()
  my_optimizer.state_averager.local_epoch = my_optimizer.tracker.global_epoch
```

As a result, if a new peer starts downloading state at epoch 100 and finishes at epoch 102, you will manually set epoch to 102 in order to __pretend__ that it is up to date.

**Comment by justheuristic** [comment]
It's also in the optimizer: https://github.com/learning-at-home/hivemind/blob/master/hivemind/optim/optimizer.py#L646

**Comment by elricwan** [comment]
Thank you.
