### ISSUE TITLE
Metaclasses for logging

### ISSUE THREAD

**Issue by StrangeTcy** [learning-at-home/hivemind#556]
It's not an actual issue or a bug report, but I just wished to ask why you used custom metaclasses to define a logger? Most people probably don't even know you could __do__ that.

**Comment by borzunov** [comment]
Hi @StrangeTcy,

Metaclasses are used for defining constants with ASCII color codes. I wanted the coloring interface so that it resembles [colorama](https://github.com/tartley/colorama#colored-output) and other popular libraries:

```python
print(f"The following text will be red: {TextStyle.RED}red text{TextStyle.RESET}")
```

The usual convention among Linux tools (e.g. `grep`) is to enable coloring when stdout is terminal and disable it when stdout is a file, so initially I wrote code like this:

```python
if sys.stdout.isatty():
    class TextStyle:
        RESET = "\033[0m"
        BOLD = "\033[1m"
        RED = "\033[31m"
        BLUE = "\033[34m"
        PURPLE = "\033[35m"
        ORANGE = "\033[38;5;208m"
else:
    class TextStyle:
        RESET = BOLD = RED = BLUE = PURPLE = ORANGE = ""

# It's not the exact code that was there, but this snippet shows the main idea
```

After a while, it turned out that it's not enough because sometimes you want to toggle coloring in your script on the fly. For example, before we added the `in_ipython()` function to hivemind, there was no convenient way to explicitly enable coloring in Jupyter/Colab in downstream apps like [Petals](https://github.com/bigscience-workshop/petals). Also, some apps may want to toggle colors if a user provides `--color` or `--no-color` args (e.g. `grep` supports this), even though hivemind is already imported.

So, I decided to write code that **(a)** keeps the previous interface with constants and **(b)** changes the values of the "constants" depending on a certain `bool` variable. The solution with metaclasses was the easiest thing that came to my mind and I'm not sure if there're easier ways of doing it (let me know if they exist).

On a second though, I guess another (maybe better) solution could be to create a function for toggling colors that replaces the whole class:

```python
def toggle_colors(enable: bool):
    global TextStyle
    if enable:
        class TextStyle:
            RESET = "\033[0m"
            BOLD = "\033[1m"
            RED = "\033[31m"
            BLUE = "\033[34m"
            PURPLE = "\033[35m"
            ORANGE = "\033[38;5;208m"
    else:
        class TextStyle:
            RESET = BOLD = RED = BLUE = PURPLE = ORANGE = ""

toggle_colors(sys.stdout.isatty() or in_ipython())  # Set default
```
